# Ülesanded

```{r label="tasks", echo=FALSE, results='asis'}
librarian::shelf(c(
  "profvis"
))
# profvis({
goals <- list(
  list(
    goal = "defineerib mis tahes nurga siinuse, koosinuse ja tangensi",
    level = 1
  ),
  list(
    goal = "teisendab kraadimõõdus antud nurga radiaanmõõtu ja vastupidi",
    level = 2
  ),
  list(
    goal = "teisendab lihtsamaid trigonomeetrilisi avaldisi (rakenduvad maksimaalselt 3 erinevat trigonomeetrilist seost)",
    level = 3
  ),
  list(
    goal = "loeb trigonomeetriliste funktsioonide graafikuid",
    level = 4
  ),
  list(
    goal = "rakendab trigonomeetriat, siinus- ja koosinusteoreemi ning kolmnurga pindala valemeid kolmnurga lahendamisel",
    level = 3
  ),
  list(
    goal = "leiab rööpküliku ja hulknurga pindala, tükeldades need sobivalt kolmnurkadeks",
    level = 4
  ),
  list(
    goal = "arvutab ringjoone kaare kui ringjoone osa pikkuse ning ringi sektori kui ringi osa pindala",
    level = 3
  ),
  list(
    goal = "lahendab lihtsamaid reaalelulise kontekstiga planimeetria probleeme",
    level = 4
  )
  
)

tasks <- list(
  list(goal = 1, level = 1, task = "Defineeri suvalise nurga siinus!"),
  list(goal = 1, level = 1, task = "Defineeri suvalise nurga koosinus!"),
  list(goal = 1, level = 1, task = "Defineeri suvalise nurga tangens!"),
  list(goal = 1, level = 2, task = "Esita näide suvalise nurga siinuse definitsiooni kohta!"),
  list(goal = 1, level = 2, task = "Esita näide suvalise nurga koosinuse definitsiooni kohta!"),
  list(goal = 1, level = 2, task = "Esita näide suvalise nurga tangensi definitsiooni kohta!"),
  list(goal = 2, level = 1, task = "Mis on nurgakraad?"),
  list(goal = 2, level = 1, task = "Kui suur on sirgnurk radiaanides ja miks?"),
  list(goal = 2, level = 1, task = "Kui suur on sirgnurk kraadides ja miks?"),
  list(goal = 2, level = 1, task = "Mis on radiaan?")
)

n_decimals_with_pi <- 16  
n_decimals_without_pi <- 16
gcd <- function(a, b) ifelse(b == 0, abs(a), Recall(b, a %% b))

generate_unique_fraction <- function(
    min_num=-9,
    max_num=9,
    min_den=1,
    max_den=9,
    max_value = Inf
) {
  
  if (max_num > 999) {
    max_num <- 999
  }
  
  if (max_den > 999) {
    max_den <- 999
  }
  
  numerators <- c(min_num:max_num)
  denominators <- c(min_den:max_den)
  fractions <- list()
  
  for (index_num in 1:length(numerators)) {
    for (index_den in 1:length(denominators)) {
      common_factor <- gcd(numerators[index_num], denominators[index_den])
      num <- numerators[index_num] / common_factor
      den <- denominators[index_den] / common_factor

      frac_str <- paste(num, den, sep = "/")
      exists <- sapply(fractions, function(x) x[[1]] == frac_str)
      
      if (!(any(exists))
          && num != 0
          && num / den <= max_value) {
        fractions <- append(fractions, list(list(frac_str, c(num, den)))) 
      }
      
    }
    
  }
  
  shuffled_list <-  fractions[sample(length(fractions))]
  sampled_fractions <- lapply(shuffled_list, `[[`, 2)
  # print(" sampled_fractions ")
  # print(sampled_fractions)
  # print(" lõpp sampled_fractions ")
  return(sampled_fractions)
}

format_latex <- function(value, with_pi = TRUE) {
  if (is.list(value) || length(value) == 2) {
    num <- value[1]
    den <- value[2]
    
    # print(" with_pi ")
    # print(with_pi)
    # print(" end with_pi ")
    if (with_pi) {
      if (num == den) {
        return("\\pi")
      } else if (num == -den) {
        return("-\\pi")
      } else if (den == 1) {
        return(paste0(num, "\\pi"))
      } else if (num < 0) {
        return(paste0("-\\frac{", abs(num), "}{", den, "} \\pi"))
      } else {
        return(paste0("\\frac{", num, "}{", den, "} \\pi"))
      }
    } else {
      if (num == den) {
        return("\\num{1}")
      } else if (num == -den) {
        return("\\num{-1}")
      } else if (den == 1) {
        return(paste0("\\num{", num, "}"))
      } else if (num < 0) {
        return(paste0("-\\frac{", abs(num), "}{", den, "}"))
      } else {
        return(paste0("\\frac{", num, "}{", den, "}"))
      }
    }
  } else { 
    
    if (with_pi) {
      if (value == 0) {
        return("0")
      } else if (value == 1) {
        return("\\pi")
      } else if (value == -1) {
        return("-\\pi")
      } else {
        return(paste0("\\num{", value, "} \\cdot \\pi"))
      }
    } else {
      if (value == 0) {
        return("0")
      } else if (value == 1) {
        return("\\num{1}")
      } else if (value == -1) {
        return("\\num{-1}")
      } else {
        return(paste0("\\num{", value, "}"))
      }
      
    }
    
  }
  
}

generate_angles <- function(
    min_decimal=-4,
    max_decimal=4,
    min_num=-9,
    max_num=9,
    min_den=1,
    max_den=9,
    max_value_with_pi=Inf, 
    min_decimal_without_pi = .1,
    max_decimal_without_pi = 2 * pi,
    n_fractions = 16,
    nought_needed = TRUE,
    as_fractions = TRUE,
    as_decimals = TRUE,
    with_pi = TRUE,
    without_pi = TRUE,
    max_value_without_pi = 2 * pi
) {
  angles_with_pi <- c()
  angles_without_pi <- c()
  
  if (as_fractions) {
    angles_fractions_with_pi <- list()
    angles_fractions_without_pi <- list()
    
    if (with_pi) {

      # for (i in 1:n_fractions) {
        
        angles_fractions_with_pi <- generate_unique_fraction(
          min_num, 
          max_num,
          min_den, 
          max_den,
          max_value = max_value_with_pi
        )
        
        # angles_fractions_with_pi[[i]] <- new_frac[[2]] 
      # }
# print(" angles_fractions_with_pi ");
# print(angles_fractions_with_pi)
# print(" lõpp angles_fractions_with_pi")
      angles_with_pi <- c(
        angles_with_pi,
        angles_fractions_with_pi
      )
      
    }
    
    if (without_pi) {
  
      # for (i in 1:n_fractions) {
        
        angles_fractions_without_pi <- generate_unique_fraction(
          min_num, 
          max_num,
          min_den, 
          max_den,
          max_value = max_value_without_pi
        )
        
        # angles_fractions_without_pi[[i]] <- new_frac[[2]] 
      # }

      angles_without_pi <- c(
        angles_without_pi,
        angles_fractions_without_pi
      )

    }
    
  }
  
  # print(" fractions with pi: ")
  # print(angles_with_pi)
  # print(" fractions with pi in latex ")
  # print(angles_with_pi)
  # print(" fractions without pi: ")
  # print(angles_without_pi)
  if (as_decimals) {
    
    if (with_pi) {
      # print(" max_decimal ")
      # print(max_decimal)
      possible_decimals_with_pi <- setdiff(
        seq(min_decimal, max_decimal, by = 0.25),
        0
      )
      
      number_of_possible_decimals_with_pi <- length(possible_decimals_with_pi)

      if (n_decimals_with_pi > number_of_possible_decimals_with_pi) {
        n_decimals_with_pi <- number_of_possible_decimals_with_pi
      }
  
      angles_decimals_with_pi <- sample(
        possible_decimals_with_pi,
        n_decimals_with_pi,
        replace = FALSE
      )
      
      angles_with_pi <- c(
        angles_with_pi,
        angles_decimals_with_pi
      )
      
    }
    # print(" decimals with pi ")
    # print(angles_decimals_with_pi)
    if (without_pi) {
      
      possible_decimals_without_pi <- setdiff(
        seq(min_decimal_without_pi, max_decimal_without_pi, by = 0.1),
        0
      )
      
      number_of_possible_decimals_without_pi <- length(possible_decimals_without_pi)
  
      angles_decimals_without_pi <- sample(
        possible_decimals_without_pi,
        n_decimals_without_pi,
        replace = FALSE
      )
      
      angles_without_pi <- c(
        angles_without_pi,
        angles_decimals_without_pi
      )

    }
    # print(" decimals without pi ")
    # print(angles_decimals_without_pi)
    
  }

  angles_with_pi <- lapply(angles_with_pi, format_latex)
  angles_without_pi <- lapply(angles_without_pi, format_latex, with_pi = FALSE)
 
  if (nought_needed) {
    
    if (runif(1) > 0.5) {
    
      angles <- c(
        angles_with_pi,
        angles_without_pi,
        list(0)
      )
  
    } else {
      
      angles <- c(
        angles_with_pi,
        angles_without_pi
       )
      
    }

  }

  return( c(
    angles
    # sapply(
  #     sample(
  #       possible_decimals_without_pi,
  #       n_decimals_without_pi, 
  #       replace = FALSE
  #     ), function(value) {
  #       return(paste("\\num{", value, "}", sep = ""))
  #     }
  #   )
    )
  )
  
}

angles_latex <- generate_angles()
# print(" angles_latex ")
# print(angles_latex)
# print(" lõpp angles_latex ")
# })


number_of_angles_in_radians <- length(angles_latex)

tasks_angles_in_radians <- lapply(1:number_of_angles_in_radians, function(i) {
  list(goal = 2, level = 2, task = paste0("Teisenda kraadidesse nurk $", angles_latex[i], "$. Näita kogu teisenduskäik!"))
  # print(" ülesanne ")
  # angles_latex[i]
  # print(" taalaga ülesanne")
  # print(paste0("$", angles_latex[i], "$"))
  # print(" lõpp ülesanne ")
})

# print(" tasks_angles_in_radians ")
# print(tasks_angles_in_radians)
# print(" lõpp tasks_angles_in_radians ")

n_degrees <- 64
angles_degrees <- sample(-720:720, n_degrees, replace = FALSE)

tasks_angles_in_degrees <- lapply(1:n_degrees, function(i) {
  list(goal = 2, level = 2, task = paste0("Teisenda radiaanidesse nurk ", angles_degrees[i], "\\degree. Suurus radiaanides peab olema täpne. Näita kogu teisenduskäik!"))
})
# print(" tasks_angles_in_degrees ")
# print(tasks_angles_in_degrees)
# print(" lõpp tasks_angles_in_degrees ")

# Creating tasks at the level 3 on radians-degrees

n_combinations <- 64  # Kombinatsioonide arv
half_straight <- n_combinations / 2  # 32 sirgnurka ja 32 mitte
combinations <- list()  # Loome tühja listi

# Kõik lubatud radiaanid, mis teisenduvad täisarvudeks kraadides (jaotur kuni 180)
valid_radian_fractions <- expand.grid(numerator = 1:179, denominator = 2:180)
valid_radian_fractions <- valid_radian_fractions[valid_radian_fractions$numerator < valid_radian_fractions$denominator, ]
valid_radian_fractions$degree <- with(valid_radian_fractions, (numerator / denominator) * 180)
valid_radian_fractions <- valid_radian_fractions[valid_radian_fractions$degree %% 1 == 0, ]  # Ainult täisarvud
# print(" valid_radian_fractions ")
# print(nrow(valid_radian_fractions))
# View(valid_radian_fractions)
# print(" lõpp valid_radian_fractions ")

# })


# Funktsioon lihtsustatud radiaanmurdude loomiseks
simplify_fraction <- function(num, denom) {
  gcd_value <- gcd(num, denom)  # Leian suurima ühisteguri
  num <- num / gcd_value
  denom <- denom / gcd_value
  return(list(latex = paste0("\\frac{", num, "}{", denom, "}\\pi"), degree = (num / denom) * 180))
}

# Funktsioon kraadinurga loomiseks (1° kuni max_value kraadi)
generate_degree <- function(max_value) {
  return(sample(1:max_value, 1))  # Ainult täisarv kraadides
}

# Funktsioon radiaaninurga valimiseks ainult sobilike seast
generate_radian <- function(degree_value) {
  valid_choices <- valid_radian_fractions[valid_radian_fractions$degree == degree_value, ]
  if (nrow(valid_choices) == 0) return(NULL)  # Tagame, et leidub õige radiaan
  chosen <- valid_choices[sample(nrow(valid_choices), 1), ]
  return(simplify_fraction(chosen$numerator, chosen$denominator))
}

# Loome 64 kombinatsiooni
for (i in 1:n_combinations) {
  is_straight <- i <= half_straight  # Esimesed 32 on sirgnurgad

  # **Loome kõigepealt kraadinurgad, et summa oleks täpne**
  angle1 <- generate_degree(178)
  angle2 <- generate_degree(179 - angle1)
  if (is_straight) {
    angle3 <- 180 - (angle1 + angle2)
  } else {
    angle3 <- generate_degree(179 - (angle1 + angle2))
  }

  # Kontrollime, et summa on õige
  sum_kraadides <- angle1 + angle2 + angle3

  # Paneme kraadinurgad listi
  angles <- c(angle1, angle2, angle3)

  # **Asendame juhuslikult ühe või kaks kraadinurka radiaanidega**
  radian_conversion_count <- sample(1:2, 1)  # Kas asendame ühe või kaks nurka?
  converted <- 0  # Loendur edukate teisenduste jaoks

  for (j in sample(1:3, 3)) {  # Käime kõik kolm nurka läbi suvalises järjekorras
    if (converted < radian_conversion_count) {
      radian_version <- generate_radian(angles[j])
      if (!is.null(radian_version)) {
        angles[j] <- paste("$", radian_version$latex, "$", sep = "")
        converted <- converted + 1
      }
    } else {
      angles[j] <- paste("$", angles[j], "\\degree$", sep = "")
    }
  }

  # Salvestame kombinatsiooni
  combinations[[i]] <- c(angles[1], angles[2], angles[3], sum_kraadides)
}

# Teisendame `data.frame`-iks, veendudes, et igal real on täpselt 4 veergu
df_combinations <- as.data.frame(do.call(rbind, combinations), stringsAsFactors = FALSE)
colnames(df_combinations) <- c("Nurk 1", "Nurk 2", "Nurk 3", "Summa kraadides")
# print(" df_combinations ")
# View(df_combinations)
# print(" lõpp df_combinations ")
# })



combinations_list <- apply(df_combinations, 1, function(row) {
  list(
    goal = 2,
    level = 3,
    task = paste("Kontrolli arvutades, kas need kolm nurka võivad olla sama kolmnurga erinevad sisenurgad: ", row[1], ", ", row[2], " ja ", row[3], ".", sep = "")
  )
})
# print(" combinations_list ")
# View(combinations_list)
# print(" lõpp combinations_list ")
# })



modification_of_expressions <- list(
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1}{[\\mathrm{cos}(\\alpha)]^2}\\cdot \\left\\{\\frac{1}{[\\mathrm{sin}(\\alpha)]^2} -1 \\right\\}.$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1}{[\\mathrm{sin}(\\alpha)]^2} - \\frac{1}{[\\mathrm{tan}(\\alpha)]^2} + [\\mathrm{tan}(\\alpha)]^2.$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$[\\mathrm{sin}(\\alpha) + \\mathrm{cos}(\\alpha)]^2 + [\\mathrm{cos}(\\alpha) - \\mathrm{sin}(\\alpha)]^2 .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$[\\mathrm{sin}(\\alpha) + \\mathrm{cos}(\\alpha)]^2 + [\\mathrm{sin}(\\alpha) - \\mathrm{cos}(\\alpha)]^2 = 2 .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\left\\{\\frac{1}{[\\mathrm{cos}(\\alpha)]^2} - 1\\right\\} \\cdot \\left\\{\\frac{1}{[\\mathrm{sin}(\\alpha)^2]} - 1\\right\\} .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1 + [\\mathrm{cos}(\\alpha)^2] - [\\mathrm{sin}(\\alpha)]^2}{\\mathrm{sin}(\\alpha) \\cdot \\mathrm{cos}(\\alpha)} .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$[\\mathrm{sin}(20\\degree) + \\mathrm{cos}(20\\degree)]^2 + [\\mathrm{sin}(20\\degree) - \\mathrm{cos}(20\\degree)]^2 .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{sin}(225\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{sin}(120\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{sin}(300\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{tan}(330\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{tan}(315\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{tan}(135\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{cos}(330\\degree) .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$\\frac{2 \\cdot [\\mathrm{sin}(\\alpha)]^2 - 1}{1 - 2 \\cdot [\\mathrm{cos}(\\alpha)]^2} = 1 .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$[1 - \\mathrm{cos}(\\alpha)]^2 + [1 + \\mathrm{cos}(\\alpha)]^2 - 4 \\cdot [\\mathrm{cos}(\\alpha)]^2 = 2 \\cdot [\\mathrm{sin}(\\alpha)]^2 .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Arvuta näidates vahesamme: $$\\mathrm{sin}(30\\degree) \\times \\mathrm{cot}(30\\degree) + \\mathrm{cos}(30\\degree)[\\mathrm{tan}(60\\degree) - \\mathrm{tan}(45\\degree)] .$$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Teisenda sekunditeks näidates vahesamme: $$\\ang{0; 45}. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Teisenda sekunditeks näidates vahesamme: $$\\ang{15}. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$\\frac{a}{b}. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$\\frac{c^2}{b^2}. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$\\frac{b}{a}. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{sin}(\\alpha) = \\num{0.39}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{sin}(\\alpha) = \\num{0.02}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{sin}(\\alpha) = \\num{1}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{sin}(\\alpha) = \\num{1.03}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{cos}(\\alpha) = \\num{2.4}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Kas on võimalik niisugune täisnurkne kolmnurk, milles $\\mathrm{cos}(\\alpha) = \\num{0.1}?$ Põhjenda!"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\mathrm{cos}(\\alpha) : \\mathrm{sin}(\\alpha) \\cdot \\mathrm{tan}(\\alpha). $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$1 - \\mathrm{tan}(\\alpha) : \\mathrm{sin}(\\alpha) : \\mathrm{cos}(\\alpha). $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$1 + [\\mathrm{cos}(\\alpha)]^2 - [\\mathrm{sin}(\\alpha)]^2. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$1 + [\\mathrm{cos}(\\alpha)]^2 - [\\mathrm{sin}(\\alpha)]^2 \\cdot [\\mathrm{cot}(\\alpha)]^2. $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\mathrm{tan}(\\qty{20}{\\degree}) \\cdot [\\mathrm{cos}(\\qty{20}{\\degree}) + 1] - \\mathrm{sin}(\\qty{20}{\\degree}) : \\mathrm{cos}(\\qty{20}{\\degree}) . $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[1 + \\mathrm{tan}(\\qty{75}{\\degree})]^2 - [1 - \\mathrm{cot}(\\qty{15}{\\degree})]^2 . $$"
  ), # 1
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$1-\\mathrm{sin}(\\alpha)\\cdot \\frac{1}{\\mathrm{tan}(\\alpha)} \\cdot \\mathrm{cos}(\\alpha).$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1 + 2 \\cdot \\mathrm{cos}(x) + \\mathrm{cos}(2 \\cdot x)}{1 - 2 \\cdot \\mathrm{cos}(x) + \\mathrm{cos}(2 \\cdot x)}.$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$1 - \\mathrm{cos}(15\\degree) \\cdot \\mathrm{cos}(75\\degree).$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$1 - \\mathrm{sin}(\\alpha) \\cdot \\mathrm{cos}(\\alpha) \\cdot \\mathrm{tan}(\\alpha) = [\\mathrm{cos}(\\alpha)]^2 .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$[\\mathrm{sin}(\\alpha)]^2 + [\\mathrm{tan}(\\alpha)]^2 + [\\mathrm{cos}(\\alpha)]^2 = [\\mathrm{cos}(\\alpha)]^{-2} .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$[\\mathrm{cos}(35\\degree)]^2 - \\mathrm{cos}(70\\degree) - [\\mathrm{sin}(35\\degree)]^2 \\times [\\mathrm{cos}(35\\degree)]^2.$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$2 \\times [\\mathrm{cos}(10\\degree)]^3 \\times \\mathrm{sin}(10\\degree) - 2 \\times [\\mathrm{sin}(10\\degree)]^3 \\times \\mathrm{cos}(10\\degree).$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\{1 - [\\mathrm{sin}(\\alpha)]^2\\} \\cdot [\\mathrm{tan}(\\alpha)]^2 - 1 .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1 - [\\mathrm{sin}(\\alpha) - \\mathrm{cos}(\\alpha)]^2}{1 - [\\mathrm{cos}(\\alpha)]^2 + [\\mathrm{sin}(\\alpha)]^2} .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Tõesta samasus: $$\\left\\{[\\mathrm{tan}(\\alpha)]^2 - [\\mathrm{sin}(\\alpha)]^2\\right\\} \\cdot \\frac{1}{[\\mathrm{tan}(\\alpha)]^2} = [\\mathrm{sin}(\\alpha)]^2 .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Tõesta samasus: $$[1 + \\mathrm{sin}(\\alpha)] \\cdot [1 - \\mathrm{sin}(\\alpha)] \\cdot [\\mathrm{tan}(\\alpha)]^2 = [\\mathrm{sin}(\\alpha)]^2 .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Tõesta samasus: $$\\left\\{1 + \\frac{1}{[\\mathrm{tan}(\\alpha)]^2}\\right\\} \\cdot \\left\\{1 - [\\mathrm{sin}(\\alpha)]^2\\right\\} = \\frac{1}{[\\mathrm{tan}(\\alpha)]^2} .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Tõesta samasus: $$\\{1 + [\\mathrm{sin}(\\alpha)]^2 - [\\mathrm{cos}(\\alpha)]^2\\} \\cdot \\frac{1}{[\\mathrm{tan}(\\alpha)]^2} = 2 \\cdot [\\mathrm{cos}(\\alpha)]^2 .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates vahesamme: $$2 \\cdot \\mathrm{sin}(\\alpha) \\cdot [\\mathrm{sin}(\\alpha) + \\mathrm{cot}(\\alpha) \\cdot \\mathrm{cos}(\\alpha)] + \\mathrm{tan}(\\alpha)[\\mathrm{tan}(\\alpha) - \\mathrm{cot}(\\alpha)] .$$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Arvuta avaldise väärtus kraadides näidates vahesamme: $$\\ang{45; 12; 44} + \\ang{17; 26; 8}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Arvuta avaldise väärtus kraadides näidates vahesamme: $$\\ang{51; 47; 26} + \\ang{22; 34; 49}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Arvuta avaldise väärtus kraadides näidates vahesamme: $$\\ang{77; 14; 18} - \\ang{37; 8; 12}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Arvuta avaldise väärtus kraadides näidates vahesamme: $$\\ang{24; 36; 38} - \\ang{10; 41; 58}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda sekunditeks näidates vahesamme: $$\\ang{42; 20; 45}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda sekunditeks näidates vahesamme: $$\\ang{10; 22; 8}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda täiskraadideks, -minutiteks ja -sekunditeks näidates vahesamme: $$\\qty{91100}{\\arcsecond}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda täiskraadideks, -minutiteks ja -sekunditeks näidates vahesamme: $$\\qty{3523}{\\arcsecond}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda täiskraadideks, -minutiteks ja -sekunditeks näidates vahesamme: $$\\qty{14535}{\\arcsecond}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Teisenda täiskraadideks, -minutiteks ja -sekunditeks näidates vahesamme: $$\\qty{4205}{\\arcsecond}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk kraadides, tulemus ümarda tuhandikeni näidates teisenduse vahesamme: $$\\ang{4; 50; 18}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk kraadides, tulemus ümarda tuhandikeni näidates teisenduse vahesamme: $$\\ang{1; 37; 19}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk kraadides, tulemus ümarda tuhandikeni näidates teisenduse vahesamme: $$\\ang{8; 4; 45}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk kraadides, tulemus ümarda tuhandikeni näidates teisenduse vahesamme: $$\\qty{55}{\\arcminute}\\qty{36}{\\arcsecond}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk täiskraadides, -minutites ja -sekundites näidates teisenduse vahesamme: $$\\qty{2.45}{\\degree}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk täiskraadides, -minutites ja -sekundites näidates teisenduse vahesamme: $$\\qty{1.91}{\\degree}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk täiskraadides, -minutites ja -sekundites näidates teisenduse vahesamme: $$\\qty{0.18}{\\degree}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Esita nurk täiskraadides, -minutites ja -sekundites näidates teisenduse vahesamme: $$\\qty{61.29}{\\degree}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$1 - \\frac{b^2}{c^2}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$\\frac{a \\cdot c}{b^2}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Täisnurkse kolmnurga kaatetid on $a$ ja $b$ ning hüpotenuus $c$. Esita antud avaldis täisnurkse kolmnurga teravnurkade siinuse, koosinuse ja tangensi kaudu näidates võimalusel vahesamme: $$\\frac{a \\cdot c}{c^2 - a^2}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$2 - \\mathrm{sin}(\\alpha) \\cdot \\mathrm{cos}(\\alpha) \\cdot \\mathrm{tan}(\\alpha). $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\frac{1}{1 + [\\mathrm{tan}(\\alpha)]^2} + [\\mathrm{sin}(\\alpha)]^2. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\frac{[\\mathrm{tan}(\\alpha)]^2}{1 + [\\mathrm{tan}(\\alpha)]^2} - 1. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[1 + \\mathrm{sin}(\\alpha)]^2 + [1 - \\mathrm{cos}(\\alpha)]^2 - 2 \\cdot \\mathrm{tan}(\\alpha) \\cdot \\mathrm{cos}(\\alpha). $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[\\mathrm{tan}(\\alpha)]^2 - \\mathrm{sin}(\\alpha) \\cdot \\mathrm{tan}(\\alpha) \\cdot [\\mathrm{tan}(\\alpha) - 1] \\cdot [\\mathrm{sin}(\\alpha) + \\mathrm{cos}(\\alpha)]. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[\\mathrm{sin}(\\alpha) + \\mathrm{\\cos}(\\alpha)] \\cdot \\mathrm{sin}(\\alpha) - [\\mathrm{cos}(\\alpha)]^2 \\cdot [\\mathrm{tan}(\\alpha) - 1]. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\mathrm{cos}(\\alpha) \\cdot [\\mathrm{sin}(\\alpha) \\dot \\mathrm{tan}(\\alpha) + \\mathrm{cos}(\\alpha)] + [\\mathrm{sin}(\\alpha)]^2 : [\\mathrm{cos}(\\alpha)]^2. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[\\mathrm{tan}(\\alpha)]^2 \\cdot \\{1 + [\\mathrm{cos}(\\alpha)]^2 + \\frac{[\\mathrm{cos}(\\alpha)]^2}{[\\mathrm{tan}(\\alpha)]^2}\\}. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[\\mathrm{cot}(\\alpha) + \\mathrm{tan}(\\alpha)] \\cdot [\\mathrm{cos}(\\alpha)]^2. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\left[1 - \\frac{1}{\\mathrm{cot}(\\alpha)}\\right] \\cdot \\left[\\mathrm{tan}(\\alpha) + \\frac{1}{[\\mathrm{cos}(\\alpha)]^2}\\right]. $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$1 + \\mathrm{tan}(\\qty{80}{\\degree}) \\cdot \\frac{\\mathrm{sin}(\\qty{80}{\\degree})}{\\mathrm{cos}(\\qty{80}{\\degree})} . $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$1 - \\frac{\\mathrm{sin}(\\qty{40}{\\degree}) \\cdot \\mathrm{cos}(\\qty{50}{\\degree}) - [\\mathrm{sin}(\\qty{50}{\\degree})]^2}{\\mathrm{sin}(\\qty{40}{\\degree}) \\cdot \\mathrm{cos}(\\qty{50}{\\degree})} . $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$\\{[\\mathrm{tan}(\\qty{10}{\\degree})]^2 - [\\mathrm{sin}(\\qty{10}{\\degree})]^2\\} : [\\mathrm{cos}(\\qty{10}{\\degree})] . $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta avaldis lõpuni näidates lahenduskäigu: $$[\\mathrm{cot}(\\alpha) + \\mathrm{tan}(\\alpha)]^2 - 1 : [\\mathrm{sin}(\\alpha)]^2 . $$"
  ), # 2
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{\\mathrm{cos}(2 \\cdot \\alpha)}{\\mathrm{cos}(\\alpha)} - \\frac{\\mathrm{sin}(2 \\cdot \\alpha)}{\\mathrm{sin}(\\alpha)}.$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Tõesta näidates vahesamme, et $$\\frac{\\mathrm{sin}(2 \\cdot x)}{1 + \\mathrm{cos}(2 \\cdot x)} \\cdot \\frac{\\mathrm{cos}(x)}{1 - [\\mathrm{cos}(x)]^2} = \\frac{1}{\\mathrm{sin}(x)}.$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme $$\\frac{[\\mathrm{sin}(2 \\cdot x)]^2 - 4 \\cdot [\\mathrm{sin}(x)]^2}{[\\mathrm{sin}(2 \\cdot x)]^2 + 4 \\cdot [\\mathrm{sin}(x)]^2 - 4}.$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme $$\\mathrm{tan}(-660\\degree)\\times [\\mathrm{cos}(720\\degree) + \\mathrm{tan}(1500\\degree)] .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme $$[\\mathrm{sin}(-270\\degree) - \\mathrm{tan}(675\\degree)] : \\mathrm{sin}(-1125\\degree) .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Kontrolli pakutud lahendit näidates vahesamme: $$[\\mathrm{sin}(90\\degree - \\alpha)]^2 - [\\mathrm{cos}(180\\degree - \\alpha)]^2 + [\\mathrm{tan}(180\\degree - \\alpha)]^2 = \\frac{1}{[\\mathrm{cos}(\\alpha)]^2} .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\frac{1}{4} \\times \\mathrm{sin}(\\frac{\\pi}{6}) \\times \\mathrm{cos}(\\frac{5 \\times \\pi}{4}) \\times \\mathrm{sin}(135\\degree) - [\\mathrm{sin}(\\frac{\\pi}{4}) + \\mathrm{cos}(315\\degree)]^2 .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$\\mathrm{sin}(\\qty{12}{\\degree}) \\cdot \\mathrm{tan}(\\qty{78}{\\degree}) \\cdot \\mathrm{cos}(\\qty{12}{\\degree}) + [\\mathrm{sin}(\\qty{12}{\\degree})]^2 .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$[1 - \\mathrm{tan}(\\qty{20}{\\degree})]^2 + [1 + \\mathrm{cot}(\\qty{70}{\\degree})]^2 .$$"
  ), # 3
  list(
    goal = 3,
    level = 3,
    task = "Lihtsusta lõpuni näidates vahesamme: $$[1 + [\\mathrm{cot}(\\qty{66}{\\degree})]^2] \\cdot [\\mathrm{cos}(\\qty{24}{\\degree})]^2 .$$"
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Kui ringjoone raadius on \\qty{5}{\\centi\\m} ja kaarele vastav kesknurk on \\qty{2.8}{\\radian}, siis kui pikk see kaar on? Esita kogu lahenduskäik!"
  ), # 1
  list(
    goal = 7,
    level = 3,
    task = "Kui sektori nurk $$x = \\qty{0.8}{\\radian}$$ ja raadius $$r = \\qty{5}{\\centi\\m},$$ siis kui suur on selle sektori pindala? Esita kogu lahenduskäik!"
  ), # 1
  list(
    goal = 7,
    level = 3,
    task = "Kui sektori raadius on \\qty{8}{\\centi\\m} ja kaare pikkus on \\qty{10}{\\centi\\m}, siis kui suur on selle sektori pindala? Esita kogu lahenduskäik!"
  ), # 1
  list(
    goal = 7,
    level = 3,
    task = "Arvuta sektori pindala ja kaare pikkus, kui kaare pikkus on \\qty{5}{\\centi\\m} ja raadius on \\qty{5}{\\centi\\m}. Esita kogu lahenduskäik!"
  ), # 1
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $$r = \\qty{90}{\\centi\\m}$$ ja kaarele vastav kesknurk on \\qty{46}{\\degree}! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $$r = \\qty{90}{\\centi\\m}$$ ja kaarele vastav kesknurk on \\qty{105}{\\degree}! Esita kogu lahenduskäik!"
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $$r = \\qty{90}{\\centi\\m}$$ ja kaarele vastav kesknurk on \\qty{200}{\\degree}! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $$r = \\qty{90}{\\centi\\m}$$ ja kaarele vastav kesknurk on \\qty{400}{\\degree}! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Arvuta sektori pindala ja kaare pikkus, kui kesknurk on \\qty{2}{\\radian} ja raadius on \\qty{5}{\\deci\\m}. Esita kogu lahenduskäik!"
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Arvuta sektori pindala ja kaare pikkus, kui kesknurk on \\qty[parse-numbers=false]{\\frac{5 \\times \\pi}{6}}{\\radian} ja raadius on \\qty{12}{\\centi\\m}. Esita kogu lahenduskäik!"
  ), # 2
  list(
    goal = 7,
    level = 3,
    task = "Ringjoone raadius on \\qty{10}{\\centi\\m}. Arvuta kesknurgale \\qty{1}{\\degree} vastava kaare pikkus millimeetrites! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Ringjoone raadius on \\qty{10}{\\centi\\m}. Arvuta kesknurgale \\qty{1}{\\arcminute} vastava kaare pikkus millimeetrites! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Ringjoone raadius on \\qty{10}{\\centi\\m}. Arvuta kesknurgale \\qty{1}{\\arcsecond} vastava kaare pikkus millimeetrites! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $r = \\qty{90}{\\centi\\m}$ ja kaarele vastav kesknurk on \\ang{54; 12}! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui raadius $$r = \\qty{90}{\\centi\\m}$$ ja kaarele vastav kesknurk on \\qty{36}{\\arcsecond}! Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui vastav kesknurk on \\ang{40; 30} ja raadius $r$ on \\qty{4}{\\centi\\m}. Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui vastav kesknurk on \\ang{40; 30} ja raadius $r$ on \\qty{500}{\\m}. Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui vastav kesknurk on \\ang{40; 30} ja raadius $r$ on \\qty{40}{\\centi\\m}. Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui vastav kesknurk on \\ang{40; 30} ja raadius $r$ on \\qty{100}{\\m}. Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta ringjoone kaare pikkus, kui vastav kesknurk on \\ang{40; 30} ja raadius $r$ on \\qty{360}{\\m}. Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Kui suur on kesknurgale \\ang{65; 15} vastava sektori pindala, kui raadius on $$r = \\qty{8}{\\centi\\m}?$$ Esita kogu lahenduskäik! Lubatud on kasutada taskuarvutit."
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta sektori pindala ja kaare pikkus, kui kesknurk on \\qty{30}{\\degree} ja raadius on \\qty{12}{\\centi\\m}. Esita kogu lahenduskäik!"
  ), # 3
  list(
    goal = 7,
    level = 3,
    task = "Arvuta sektori pindala ja kaare pikkus, kui kesknurk on \\qty{114}{\\degree} ja raadius on \\qty{30}{\\centi\\m}. Esita kogu lahenduskäik!"
  ) # 3
)
# print(" modification_of_expressions ")
# View(modification_of_expressions)
# print(" lõpp modification_of_expressions ")
# })



# Sector

# print(" angles latex central ")

angles_latex_central <- generate_angles(
  min_decimal = .25,
  max_decimal = 2,
  min_num=1,
  max_num=10,
  min_den=1,
  max_den=10,
  max_value_with_pi = 2,
  min_decimal_without_pi = .1,
  max_decimal_without_pi = 2 * pi,
  n_fractions = 8,
  with_pi = TRUE,
  without_pi = TRUE,
  max_value_without_pi = 2 * pi
)
# print(" angles_latex_central ")
# View(angles_latex_central)
# print(" lõpp angles_latex_central ")
# })



angles_latex_border <- generate_angles(
  min_decimal = .25,
  max_decimal = 1,
  min_num=1,
  max_num=10,
  min_den=1,
  max_den=10,
  max_value_with_pi = 1,
  min_decimal_without_pi = .1,
  max_decimal_without_pi = pi,
  n_fractions = 8,
  with_pi = TRUE,
  without_pi = TRUE,
  max_value_without_pi = pi
)
# print(" angles_latex_border ")
# View(angles_latex_border)
# print(" lõpp angles_latex_border ")
# })



number_of_angles_central <- length(angles_latex_central)
number_of_angles_border <- length(angles_latex_border)

tasks_arc_length_by_central_angle_and_radius <- lapply(
  1:number_of_angles_central,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori kaar, kui kesknurk on $", 
        angles_latex_central[i],
        "$ ja raadius on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_arc_length_by_central_angle_and_radius ")
# View(tasks_arc_length_by_central_angle_and_radius)
# print(" lõpp tasks_arc_length_by_central_angle_and_radius ")
# })



tasks_arc_length_by_central_angle_and_diameter <- lapply(
  1:number_of_angles_central,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori kaar, kui kesknurk on $", 
        angles_latex_central[i],
        "$ ja diameeter on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_arc_length_by_central_angle_and_diameter ")
# View(tasks_arc_length_by_central_angle_and_diameter)
# print(" lõpp tasks_arc_length_by_central_angle_and_diameter ")
# })



tasks_arc_length_by_border_angle_and_radius <- lapply(
  1:number_of_angles_border,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori kaar, kui piirdenurk on $", 
        angles_latex_border[i],
        "$ ja raadius on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_arc_length_by_border_angle_and_radius ")
# View(tasks_arc_length_by_border_angle_and_radius)
# print(" lõpp tasks_arc_length_by_border_angle_and_radius ")
# })



tasks_arc_length_by_border_angle_and_diameter <- lapply(
  1:number_of_angles_border,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori kaar, kui piirdenurk on $", 
        angles_latex_central[i],
        "$ ja diameeter on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_arc_length_by_border_angle_and_diameter ")
# View(tasks_arc_length_by_border_angle_and_diameter)
# print(" lõpp tasks_arc_length_by_border_angle_and_diameter ")
# })



tasks_sector_area_by_central_angle_and_radius <- lapply(
  1:number_of_angles_central,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori pindala, kui kesknurk on $", 
        angles_latex_central[i],
        "$ ja raadius on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)

# print(" tasks_sector_area_by_central_angle_and_radius ")
# View(tasks_sector_area_by_central_angle_and_radius)
# print(" lõpp tasks_sector_area_by_central_angle_and_radius ")
# })



tasks_sector_area_by_central_angle_and_diameter <- lapply(
  1:number_of_angles_central,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori pindala, kui kesknurk on $", 
        angles_latex_central[i],
        "$ ja diameeter on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_sector_area_by_central_angle_and_diameter ")
# View(tasks_sector_area_by_central_angle_and_diameter)
# print(" lõpp tasks_sector_area_by_central_angle_and_diameter ")
# })



tasks_sector_area_by_border_angle_and_radius <- lapply(
  1:number_of_angles_border,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori pindala, kui piirdenurk on $", 
        angles_latex_border[i],
        "$ ja raadius on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_sector_area_by_border_angle_and_radius ")
# View(tasks_sector_area_by_border_angle_and_radius)
# print(" lõpp tasks_sector_area_by_border_angle_and_radius ")
# })



tasks_sector_area_by_border_angle_and_diameter <- lapply(
  1:number_of_angles_border,
  function(i) {
    list(
      goal = 7, 
      level = 3,
      task = paste0(
        "Arvuta sektori pindala, kui piirdenurk on $", 
        angles_latex_central[i],
        "$ ja diameeter on \\num{",
        sample(x = 1:64, size = 1), 
        "}. Näita kogu arvutuskäik!"
      )
    )
  }
)
# print(" tasks_sector_area_by_border_angle_and_diameter ")
# View(tasks_sector_area_by_border_angle_and_diameter)
# print(" lõpp tasks_sector_area_by_border_angle_and_diameter ")
# })



# Putting together all the tasks

tasks <- c(
  tasks,
  tasks_angles_in_radians, # 250
  tasks_angles_in_degrees, # 64
  combinations_list, # 64
  modification_of_expressions, # 116
  tasks_arc_length_by_central_angle_and_radius, # 132
  tasks_arc_length_by_central_angle_and_diameter, # 131
  tasks_arc_length_by_border_angle_and_radius, # 106
  tasks_arc_length_by_border_angle_and_diameter, # 105
  tasks_sector_area_by_central_angle_and_radius, # 132
  tasks_sector_area_by_central_angle_and_diameter, # 132
  tasks_sector_area_by_border_angle_and_radius, # 105
  tasks_sector_area_by_border_angle_and_diameter # 105
)

# print(" tasks ")
# View(tasks)
# print(" lõpp tasks ")
# })



# Kontrolli, kas tasks sees on kusagil vektor task-väljal
# probleemsed <- sapply(tasks, function(x) length(x$task) > 1)
# which(probleemsed) # annab indeksi, kus probleem tekib
# print(" proble ")
# print(tasks[probleemsed]) # kuvab täpse probleemi koha
# print(" lõpp proble ")

dataframe_tasks <- do.call(rbind, lapply(tasks, as.data.frame, stringsAsFactors = FALSE))
number_goals <- length(goals)

librarian::shelf(c(
  "dplyr"
))

number_of_pupils <- 64

goals_in_use <- unique(dataframe_tasks$goal)
# print(" dataframe_tasks ")
# print(dataframe_tasks)
# print(" lõpp dataframe_tasks ")
number_of_goals_in_use <- length(goals_in_use)
random_sample_df <- function(df, new_size) { # 64
  base_size <- floor(new_size / nrow(df))  
  remaining <- new_size %% nrow(df)

  repeated_df <- df[rep(1:nrow(df), each = base_size), , drop = FALSE]

  extra_rows <- df[sample(1:nrow(df), remaining, replace = FALSE), , drop = FALSE]

  final_df <- rbind(repeated_df, extra_rows)
  final_df <- final_df[sample(1:nrow(final_df)), , drop = FALSE]

  return(final_df)
}

number_of_tasks_at_level_per_pupil <- 8 # 8
# number_of_tasks <- number_of_pupils * number_of_tasks_at_level_per_pupil
 
number_of_tasks <- nrow(dataframe_tasks)
df_segatud <- dataframe_tasks[sample(number_of_tasks), ]
arranged_sampled_tasks <- arrange(df_segatud, goal, level)
# print(" arranged_sampled_tasks ")
# View(arranged_sampled_tasks)
# print(" lõpp arranged_sampled_tasks ")
# })



# chosen_tasks <- c()
# # })
# 
# 
# for (index_of_task in 1:number_of_tasks) { # 1-512
# 
#   for (index in 1:number_of_goals_in_use) {
#     tasks_of_goal <- subset(arranged_sampled_tasks, goals_in_use[index] == `goal`)
#     levels_in_use <- unique(tasks_of_goal$level)
#     number_of_levels_in_use <- length(levels_in_use)
#     
#     for (index_of_level in 1:number_of_levels_in_use) {
#       tasks_at_level <- subset(tasks_of_goal, levels_in_use[index_of_level] == `level`)
#       print(" number tasks_at_level ")
#       print(goals_in_use[index])
#       print(levels_in_use[index_of_level])
#       print(nrow(tasks_at_level))
#       print(" lõpp number tasks_at_level ")
#       # sampled_tasks_at_level <- random_sample_df(df = tasks_at_level, new_size = number_of_pupils)
#       if (number_of_tasks_at_level_per_pupil > nrow(tasks_at_level)) {
#         number_of_chosen_tasks_at_level <- nrow(tasks_at_level)
#       } else {
#         number_of_chosen_tasks_at_level <- number_of_tasks_at_level_per_pupil
#       }
#       if (length(chosen_tasks) > 0) {
#         chosen_tasks <- rbind(chosen_tasks, tasks_at_level[1:number_of_chosen_tasks_at_level, ])
#       } else {
#         chosen_tasks <- tasks_at_level[1:number_of_chosen_tasks_at_level, ]
#       }
#       
#     }
#       
#   }
#   
# }
# print(" unique sampled_tasks ")
# print(unique(sampled_tasks$task[grep("c\\(", sampled_tasks$task)]))
# print(" lõpp unique ")
# probleemsed_taskid <- sampled_tasks[grep("c\\(", sampled_tasks$task), ]
# print(probleemsed_taskid)
# print(" täitsa lõpp unique ")
# sampled_tasks <- arrange(sampled_tasks, goal, level)
# })

```




## Üks ülesanne õpilase kohta

```{r label="list-of-tasks-one-per-pupil", echo=FALSE, results='asis'}
# profvis({

for (index_of_pupil in 1:number_of_pupils) {
  cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))

  for (index in 1:number_of_goals_in_use) {
    # print(" index_goals_in_use ")
    # print(index)
    # print(" lõpp index_goals_in_use ")
    cat(paste(
      "**\\color[hsb]{0.",
      goals[[goals_in_use[index]]]$level - 1,
      ", 1, 1}{Õpiväljund:}** Õpilane ",
      goals[[goals_in_use[index]]]$goal,
      ".\n\n", 
      sep = ""
    ))
    
    # tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
    # levels_in_use <- unique(x = tasks_of_goal$level)
    # number_of_levels_in_use <- length(levels_in_use)

    for (index_of_levels in 1:5) {
      tasks_goal_level <- subset(arranged_sampled_tasks, index_of_levels == `level` & goals_in_use[index] == `goal`)
      number_of_tasks_goal_level <- nrow(tasks_goal_level)
      if (number_of_tasks_goal_level > 0) {
        
        cat(
          "**",
          index_of_levels,
          ". taseme ülesanne:** ",
          sep = ""
        )
      
        cat(tasks_goal_level[index_of_pupil %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
      }

      # tasks_at_level <- subset(
      #   tasks_of_goal,
      #   levels_in_use[index_of_levels] == `level`
      # )
    }

  }

}

# })

```

## Mitu ülesannet õpilase kohta

```{r label="tasks-many-per-pupil", echo=FALSE, results='asis'}

for (index_of_pupil in 1:number_of_pupils) {
  cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))

  for (index in 1:number_of_goals_in_use) {
    # print(" index_goals_in_use ")
    # print(index)
    # print(" lõpp index_goals_in_use ")
    cat(paste(
      "**\\color[hsb]{0.",
      goals[[goals_in_use[index]]]$level - 1,
      ", 1, .75}{Õpiväljund:}** Õpilane ",
      goals[[goals_in_use[index]]]$goal,
      ".\n\n", 
      sep = ""
    ))
    
    # tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
    # levels_in_use <- unique(x = tasks_of_goal$level)
    # number_of_levels_in_use <- length(levels_in_use)

    for (index_of_levels in 1:5) {
      tasks_goal_level <- subset(arranged_sampled_tasks, index_of_levels == `level` & goals_in_use[index] == `goal`)
      number_of_tasks_goal_level <- nrow(tasks_goal_level)
      if (number_of_tasks_goal_level > 1) {
        
        cat(
          "**",
          index_of_levels,
          ". taseme ülesanded:**\n\n",
          sep = ""
        )
      
        # cat(tasks_goal_level[index_of_pupil %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
      } else if (number_of_tasks_goal_level > 0) {
        
        cat(
          "**",
          index_of_levels,
          ". taseme ülesanne:** ",
          sep = ""
        )
        
      }
      
      if (number_of_tasks_goal_level > 0) {
        max_number_of_tasks <- 8 - 1
        for (index_of_task_goal_level in 0:max_number_of_tasks) {
          
          cat("a. ", tasks_goal_level[(index_of_pupil + index_of_task_goal_level) %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
        }
      }

      # tasks_at_level <- subset(
      #   tasks_of_goal,
      #   levels_in_use[index_of_levels] == `level`
      # )
    }

  }

}
# current_pupil <- 1
# 
# for (index_of_pupil in 1:number_of_pupils) {
#   cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))
# 
#   for (index in 1:number_of_goals_in_use) {
#     
#     cat(paste(
#       "**\\color[hsb]{0.",
#       goals[[goals_in_use[index]]]$level - 1,
#       ", 1, 1}{Õpiväljund:}** Õpilane ",
#       goals[[goals_in_use[index]]]$goal,
#       ".\n\n", 
#       sep = ""
#     ))
# 
#     tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
#     levels_in_use <- unique(x = tasks_of_goal$level)
#     number_of_levels_in_use <- length(levels_in_use)
# 
#     for (index_of_levels in 1:number_of_levels_in_use) {
#           
#       cat(
#         "**",
#         levels_in_use[index_of_levels],
#         ". taseme ülesanded:**\n\n ",
#         sep = ""
#       )
# 
#       tasks_at_level <- subset(
#         tasks_of_goal,
#         levels_in_use[index_of_levels] == `level`
#       )
#       
#       number_of_tasks_at_level <- nrow(tasks_at_level)
#       last_task_for_pupil <- current_pupil + number_of_tasks_at_level_per_pupil - 1
#       
#       for (index_of_task in current_pupil:last_task_for_pupil) {
#         cat(index_of_task, ". ", tasks_at_level[index_of_task, ]$task, "\n\n", sep = "")
#       }
#       
#       current_pupil <- current_pupil + number_of_tasks_at_level_per_pupil
#     }
# 
#   }
# 
# }

```

